### ISSUE TITLE
Migrate workflow from functions to object/methods

### ISSUE THREAD

**Issue by russelldj** [open-forest-observatory/automate-metashape#55]
Suggested by @youngdjn. I forget the exact reasoning, but I believe it was to provide more explicit control of global variables.

**Comment by russelldj** [comment]
Currently, all of the functions take the the metashape document argument `doc` which is updated in each function. This could be somewhat confusing to users who wouldn't expect this pattern and is also redundant. Moving to an object-oriented approach where each step is a method, and making `doc` a class attribute, would make this types of "side effects" more expected.

**Comment by asidhu0** [comment]
@youngdjn Would it be a good idea to add the `read_yaml` functions to the class also so that I can make `cfg` a class attribute also?

**Comment by youngdjn** [comment]
Couldn't you still make `cfg` a class attribute if the yaml was parsed in advance, outside the class? That said, I think it makes sense to include the yaml read in the class, as then perhaps we could instantiate the workflow object by passing it a path to the yaml file.

**Comment by youngdjn** [comment]
(Note that `cfg` currently is not a filepath, but rather a list resulting from parsing the yaml file)

**Comment by asidhu0** [comment]
> Couldn't you still make `cfg` a class attribute if the yaml was parsed in advance, outside the class? That said, I think it makes sense to include the yaml read in the class, as then perhaps we could instantiate the workflow object by passing it a path to the yaml file.

Yeah, that is true because then I would pass `cfg` into the `init()` method of the class. Sorry, I phrased my question incorrectly. I mainly wanted to know whether it would be a good idea to move the two functions in the `read_yaml.py` file (`read_yaml()` and `convert_objects()`) into the class. If so, I had the same idea as you that we instantiate the object just by passing it a path to the yaml file. Then the next step would be to call the `project_setup()` method.

**Comment by youngdjn** [comment]
Cool, yes that sounds great to me!

**Comment by russelldj** [comment]
Closed by #59
